//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xiaowen.SqlDetach.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemoTb
    {
        public int Id { get; set; }
        public string Author { get; set; }
        public string Email { get; set; }
        public string Alias { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
